In [1]:
# utf-8
import QUANTAXIS as QA

market = QA.QA_Market(if_start_orderthreading=True)
user = QA.QA_Portfolio()
# 创建两个account
# 这里是创建一个资产组合,然后在组合里面创建两个account  你可以想象成股票里面的两个策略账户
# 然后返回的是这个账户的id
a_1 = user.new_account()
a_1.reset_assets(100000000)
a_1.frequence = QA.FREQUENCE.ONE_MIN
market.start()

market.connect(QA.BROKER_TYPE.BACKETEST)

QUANTAXIS>> start QUANTAXIS
QUANTAXIS>> Welcome to QUANTAXIS, the Version is 1.1.0
QUANTAXIS>>
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``########`````##````````##``````````##`````````####````````##```##########````````#``````##``````###```##`````######``
  `##``````## ```##````````##`````````####````````##`##```````##```````##```````````###``````##````##`````##```##`````##`
  ##````````##```##````````##````````##`##````````##``##``````##```````##``````````####```````#```##``````##```##``````##
  ##````````##```##````````##```````##```##```````##```##`````##```````##`````````##`##```````##`##```````##````##```````
  ##````````##```##````````##``````##`````##``````##````##````##```````##````````##``###```````###````````##`````##``````
  ##````````##```##````````##``````##``````##`````##`````##```##```````##```````##````##```````###````````##``````###````
  ##````````##```##````````##`````##````````##````##``````##``##```````##``````##``````##`````##`##```````##````````##```
  ##````````##```##````````##````#############````##```````##`##```````##`````###########`````##``##``````##`````````##``
  ###```````##```##````````##```##```````````##```##```````##`##```````##````##`````````##```##```##``````##```##`````##`
  `##``````###````##``````###``##`````````````##``##````````####```````##```##``````````##``###````##`````##````##`````##
  ``#########``````########```##``````````````###`##``````````##```````##``##````````````##`##``````##````##`````###``###
  ````````#####`````````````````````````````````````````````````````````````````````````````````````````````````````##``
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``````````````````````````Copyright``yutiansut``2018``````QUANTITATIVE FINANCIAL FRAMEWORK`````````````````````````````
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

True

In [2]:
import threading

In [3]:
threading.enumerate()

[<_MainThread(MainThread, started 27768)>,
 <Thread(Thread-4, started daemon 4480)>,
 <Heartbeat(Thread-5, started daemon 24320)>,
 <HistorySavingThread(IPythonHistorySavingThread, started 10944)>,
 <ParentPollerWindows(Thread-3, started daemon 7012)>,
 <Thread(pymongo_server_monitor_thread, started daemon 24500)>,
 <Thread(pymongo_kill_cursors_thread, started daemon 20944)>,
 <Thread(pymongo_kill_cursors_thread, started daemon 14344)>,
  <QA_ENGINE with ['ORDER', 'backtest'] kernels ident 21644>,
 <QA_ThreadORDER  id=2149974935480 ident 24736>,
 <QA_Threadbacktest  id=2150063816432 ident 12152>]

In [4]:
market.login(QA.BROKER_TYPE.BACKETEST, a_1.account_cookie, a_1)
market._sync_orders()

In [5]:
for code in ['000001', '000002', '000004', '600010', '000007','600000']:
    market.insert_order(a_1.account_cookie,code=code,
                            price=0,
                            amount=1000,
                            time='2018-08-14 14:58:00',
                            towards=QA.ORDER_DIRECTION.BUY,
                            order_model=QA.ORDER_MODEL.MARKET,
                            amount_model=QA.AMOUNT_MODEL.BY_AMOUNT,
                            market_type=QA.MARKET_TYPE.STOCK_CN,
                            frequence=QA.FREQUENCE.ONE_MIN,
                            broker_name=QA.BROKER_TYPE.BACKETEST,
    )

QUANTAXIS>> MARKET WARING: SOMEING WRONG WITH ORDER

QUANTAXIS>> code 000001 date 2018-08-14 14:58:00 price 0 order_model MARKET amount_model by_amount
QUANTAXIS>> MARKET WARING: SOMEING WRONG WITH ORDER

QUANTAXIS>> code 000004 date 2018-08-14 14:58:00 price 0 order_model MARKET amount_model by_amount

In [13]:
market.order_handler.deal_status

                                        trade_time    code  name  towards  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk  2018-08-14 14:58:00  000002  None        1
               Order_qpcyuUQ2  2018-08-14 14:58:00  600010  None        1
               Order_c8A5fQdZ  2018-08-14 14:58:00  000007  None        1
               Order_drBj4fmc  2018-08-14 14:58:00  600000  None        1

                               trade_amount  trade_price  trade_money  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk          1000        22.33   22335.5825
               Order_qpcyuUQ2          1000         1.63    1635.0000
               Order_c8A5fQdZ             0         0.00       5.0000
               Order_drBj4fmc          1000        10.07   10070.0000

                                     trade_id
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk  Trade_oGO6qEYr
               Order_qpcyuUQ2  Trade_wUeO0MRD
               Order_c8A5fQdZ  Trade_3NUIzrBG
               Order_drBj4fmc  Trade_jOpQTDyC

In [12]:
market.broker[QA.BROKER_TYPE.BACKETEST].query_orders(a_1.account_cookie,'')

                                        order_time    code  name  towards  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk  2018-08-14 14:58:00  000002  None        1
               Order_qpcyuUQ2  2018-08-14 14:58:00  600010  None        1
               Order_c8A5fQdZ  2018-08-14 14:58:00  000007  None        1
               Order_drBj4fmc  2018-08-14 14:58:00  600000  None        1

                               trade_price  order_price             status  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk        22.33       22.330      trade_success
               Order_qpcyuUQ2         1.63        1.630      trade_success
               Order_c8A5fQdZ         0.00       13.230  trade_price_limit
               Order_drBj4fmc        10.07       10.065      trade_success

                               order_amount  trade_amount  cancel_amount
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk          1000          1000              0
               Order_qpcyuUQ2          1000          1000              0
               Order_c8A5fQdZ          1000             0              0
               Order_drBj4fmc          1000          1000              0

In [11]:
market.broker[QA.BROKER_TYPE.BACKETEST].query_orders(a_1.account_cookie,'filled')

                                        trade_time    code  name  towards  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk  2018-08-14 14:58:00  000002  None        1
               Order_qpcyuUQ2  2018-08-14 14:58:00  600010  None        1
               Order_c8A5fQdZ  2018-08-14 14:58:00  000007  None        1
               Order_drBj4fmc  2018-08-14 14:58:00  600000  None        1

                               trade_amount  trade_price  trade_money  \
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk          1000        22.33   22335.5825
               Order_qpcyuUQ2          1000         1.63    1635.0000
               Order_c8A5fQdZ             0         0.00       5.0000
               Order_drBj4fmc          1000        10.07   10070.0000

                                     trade_id
account_cookie realorder_id
Acc_6RE1dcY4   Order_u2Wia8Xk  Trade_oGO6qEYr
               Order_qpcyuUQ2  Trade_wUeO0MRD
               Order_c8A5fQdZ  Trade_3NUIzrBG
               Order_drBj4fmc  Trade_jOpQTDyC

In [10]:
a_1.history_table

,datetime,code,price,amount,cash,order_id,realorder_id,trade_id,account_cookie,commission,tax
0,2018-08-14 14:58:00,000002,22.33,1000,9.997763e+07,Order_u2Wia8Xk,Order_u2Wia8Xk,Trade_oGO6qEYr,Acc_6RE1dcY4,5.5825,33.495
1,2018-08-14 14:58:00,600010,1.63,1000,9.997600e+07,Order_qpcyuUQ2,Order_qpcyuUQ2,Trade_wUeO0MRD,Acc_6RE1dcY4,0.4075,2.445
2,2018-08-14 14:58:00,600000,10.07,1000,9.996591e+07,Order_drBj4fmc,Order_drBj4fmc,Trade_jOpQTDyC,Acc_6RE1dcY4,2.5175,15.105